#레벨 버프 주문서
#boostper : 경험치 증가량, second : 버프 유지 시간
#증가율 뒤에는 반드시 %가 있어야 합니다.
#지속시간 뒤에는 반드시 초가 있어야 합니다.
#예시 : boosrper%만큼, 지속시간 : second초 이렇게 해야지 재대로 적용이 됩니다.
levelup_buf:
  custom_model: ""
  type: PAPER
  name: "&a경험치 부스트 주문서"
  lore:
    - "&e경험치 획득량이 boostper%만큼 second초 동안 얻는 경험치가 증가합니다."

#레벨업 주문서
#level : 레벨업할 수치
levelup:
  custom_model: ""
  type: PAPER
  name: "&a레벨업 주문서"
  lore:
    - "&e사용시, level레벨을 레벨업 합니다."


#사운드 설정
#정확한 영어 이름을 입력해야 재대로 적용이 됩니다.(소리가 잘못 설정되면 기본값으로 자동으로 설정됩니다.)

#경험치 버프 주문서를 사용했을시 나오는 소리
Exp_buf_sound: "ENTITY_WITCH_AMBIENT"

#레벨업 쿠폰을 사용했을때 나오는 소리
levelup_sound: "ENTITY_PLAYER_LEVELUP"